[tool.poetry]
authors = ["laurent"]
description = "unet"
name = "unet"
version = "0.1.0"

[tool.poetry.dependencies]
albumentations = "^1.2.0"
matplotlib = "^3.5.2"
numpy = "^1.23.0"
onnx = "^1.12.0"
onnxruntime = "^1.11.1"
python = ">=3.8,<3.11"
pytorch-lightning = "^1.6.4"
rich = "^12.4.4"
scipy = "^1.8.1"
torch = "1.11.0"
torchvision = "^0.12.0"
tqdm = "^4.64.0"
wandb = "^0.12.19"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
ipykernel = "^6.15.0"
isort = "^5.10.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
exclude = '''
/(
  \.git
  \.venv
)/
'''
include = '\.pyi?$'
line-length = 120
target-version = ["py310"]

[tool.isort]
multi_line_output = 3
profile = "black"
