FROM python:3

# WORKDIR /workspace

# RUN pip install --upgrade pip --no-input
# RUN curl -sSL https://install.python-poetry.org | python3 -

# RUN echo 'export PATH="$PATH:/root/.local/bin"' >> /root/.bashrc
# RUN echo '/root/.local/bin/poetry install --no-interaction' >> /root/.bashrc
# RUN echo '/root/.local/bin/poetry shell' >> /root/.bashrc

# SHELL ["/bin/bash", "-ec"]
