version: "3"

services:
  # wandb dashboard
  wandb:
    hostname: wandb-local
    container_name: wandb-local
    image: wandb/local
    volumes:
      - ./wandb-local/:/vol
    ports:
      - 8080:8080
    restart: unless-stopped

  # development container
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true
    network_mode: service:wandb
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
